### ISSUE TITLE
Automatic PNG conversion

### ISSUE THREAD

**Issue by benwa** [blazcode/BgAssist#2]
BgInfo doesn't support PNGs, however users might still set a PNG as their wallpaper. This will cause the wallpaper to be a solid black. If possible, can BgAssist automatically convert PNGs to JPGs before running BgInfo?

**Comment by blazcode** [comment]
Hey @benwa - You're correct, BgInfo doesn't support .pngs. BgAssist is currently written to leverage administrator predefined .bgi configuration files. The configuraiton files and associated background images should be set in adavance for users if BgAssist is being used as intended. I think time is better invested in converting .pngs to .jpg before setting up a .bgi configuration versus augmenting BgAssist with the functionality

If you've found a use case for BgAssist that I didn't consider, fire up a discussion thread with the details.
