### ISSUE TITLE
Hide Tray Icon

### ISSUE THREAD

**Issue by benwa** [blazcode/BgAssist#3]
I'd like to be able to hide the BgAssist tray icon from users' desktops.

**Comment by blazcode** [comment]
Great idea. This might be possible - let me look into it.

**Comment by blazcode** [comment]
@benwa - Would you mind testing this build and providing feedback on the feature?

![image](https://user-images.githubusercontent.com/58145113/101999197-8493a780-3cd2-11eb-9e67-43caed92794d.png)
[BgAssist - 1.2.2 Beta.zip](https://github.com/blazcode/BgAssist/files/5683936/BgAssist.-.1.2.2.Beta.zip)

Thanks!

**Comment by benwa** [comment]
Works great!

**Comment by blazcode** [comment]
Awesome, thanks! I'll have this included in 1.2.2 soon along with a fix for issue #5.
